[font]
size = 12.0

[font.bold]
family = "NotoMono NF"
style = "Bold"

[font.bold_italic]
family = "NotoMono NF"
style = "Bold Italic"

[font.italic]
family = "NotoMono NF"
style = "Italic"

[font.normal]
family = "NotoMono NF"
style = "Regular"

[window]
title = "Alacritty"
opacity = 0.89
decorations = "full"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "C", mods = "Alt", action = "Copy" },
  { key = "V", mods = "Alt", action = "Paste" },
  { key = "Q", mods = "Control", action = "Quit" },
  { key = "Return", mods = "Control", action = "ToggleFullscreen" },
  { key = "N", mods = "Control", action = "SpawnNewInstance" },
  { key = "Space", mods = "Alt", chars = " " },
  { key = "Back", mods = "Super", chars = "\u001b\u004f" },                    # delete word/line
  { key = "Left", mods = "Alt", chars = "\u001BB" },                           # one word left
  { key = "Right", mods = "Alt", chars = "\u001BF" },                          # one word right
  { key = "Left", mods = "Control", chars = "\u001bOH", mode = "AppCursor" },  # Home
  { key = "Right", mods = "Control", chars = "\u001bOF", mode = "AppCursor" }, # End
]
